server:
  port: 8989
  servlet:
    context-path: /bank-api

spring:
  security:
    user:
      name: bankapp
      password: changeit
  h2:
    console:
      enabled: true
  threads:
    virtual:
      enabled: true

# SpringDoc OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
